[build]
  base = "client"
  command = "npm run build"
  publish = ".next"

[build.environment]
  DATABASE_URL = "postgresql://admin:1234@localhost:5432/semantic"

[[plugins]]
  package = "@netlify/plugin-nextjs"
